name: Nextflow Lint [WIP]

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ohsu-cedar-comp-hub/WGS-nextflow-workflow@main
